import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import styles from "./a-propos.module.css";
import AboutMotionEffects from "./AboutMotionEffects";

export const metadata: Metadata = { title: "À propos | Mahaty Pharm", description: "Découvrez Mahaty Pharm, partenaire médical basé à Bamako pour la formation, la représentation médicale et la gestion administrative." };
const nav = [["Accueil", "/"], ["Services", "/services"], ["À propos", "/a-propos"], ["Contact", "/contact"]];

function Logo({ priority=false }:{ priority?:boolean }) { return <Image className={styles.logo} src="/Logo.jpg" alt="Logo Mahaty Pharm" width={1290} height={1287} sizes="(max-width:899px) 56px, 78px" priority={priority}/>; }
function Header(){return <><div className={styles.strip}><span>Bamako, Mali</span><a href="https://wa.me/22377777777" target="_blank" rel="noopener noreferrer">Nous contacter</a></div><header className={styles.header}><div className={styles.headerIn}><Link href="/" aria-label="Accueil Mahaty Pharm"><Logo priority/></Link><nav className={styles.desktopNav}>{nav.map(([l,h])=><Link className={h==="/a-propos"?styles.active:""} href={h} key={h}>{l}</Link>)}</nav><Link className={styles.headerCta} href="/contact">Proposer un partenariat</Link><details className={styles.menu}><summary aria-label="Ouvrir le menu"><i/><i/><i/></summary><nav>{nav.map(([l,h])=><Link className={h==="/a-propos"?styles.active:""} href={h} key={h}>{l}</Link>)}</nav></details></div></header></>}
function Footer(){return <footer className={styles.footer}><div className={styles.footerIn}><Logo/><div className={styles.footerInfo}><h2>Mahaty</h2><p>Formation des délégués • Représentation médicale • Gestion administrative</p><strong>Bamako, Mali</strong><div><a href="https://wa.me/22377777777" target="_blank" rel="noopener noreferrer">+223 77 77 77 77</a><a href="mailto:Mahatycontact@gmail.com">Mahatycontact@gmail.com</a></div><small>© 2026 Mahaty. Tous droits réservés.</small></div><nav>{nav.map(([l,h])=><Link href={h} key={h}>{l}</Link>)}</nav></div></footer>}
function RepereIcon({type}:{type:"experience"|"network"|"location"}){return <svg viewBox="0 0 64 64" aria-hidden="true">{type==="experience"?<><circle cx="32" cy="25" r="17"/><path d="m21 40-5 18 16-8 16 8-5-18"/></>:type==="network"?<><circle cx="32" cy="13" r="8"/><circle cx="13" cy="49" r="8"/><circle cx="51" cy="49" r="8"/><path d="m28 20-11 22m19-22 11 22M21 49h22"/></>:<><path d="M32 59S14 40 14 24a18 18 0 1 1 36 0c0 16-18 35-18 35Z"/><circle cx="32" cy="24" r="7"/></>}</svg>}

export default function AboutPage(){return <main className={styles.page} data-page="about"><Header/>
  <section className={styles.hero}><div className={styles.heroIn}><div className={styles.heroCopy}><span className={styles.heroEyebrow}>À propos de Mahaty</span><h1 className={styles.heroHeading}>Une présence médicale structurée au cœur de Bamako.</h1><p className={styles.heroLead}>Mahaty accompagne les acteurs de la santé qui recherchent une équipe locale pour former leurs délégués, représenter leur offre et organiser le suivi de leurs activités au Mali.</p><div className={styles.actions}><Link className={`${styles.primary} ${styles.heroPrimary}`} href="/services">Découvrir nos services</Link><Link className={`${styles.secondary} ${styles.heroSecondary}`} href="/contact">Nous contacter</Link></div></div><div className={styles.heroImage}><Image src="/image/a-propos-hero-bureau.jpg" alt="Locaux de Mahaty Pharm à Bamako" fill sizes="(max-width:899px) calc(100vw - 40px), 560px" priority/><i/><b/></div></div></section>
  <section className={styles.who}><div className={styles.twoCol}><div className={styles.whoImage} data-reveal><Image src="/image/a-propos-hero-equipe.jpg" alt="Équipe de Mahaty Pharm" fill sizes="(max-width:899px) calc(100vw - 40px), 520px"/></div><div className={styles.whoText} data-reveal><span className={styles.eyebrow}>Qui sommes-nous ?</span><h2>Un partenaire local pour les acteurs de la santé.</h2><p data-reveal>Basée à Bamako, Mahaty travaille aux côtés des laboratoires, distributeurs, marques et structures de santé qui ont besoin d’une présence organisée sur le terrain.</p><p data-reveal>Notre rôle est de mettre à leur disposition les compétences, le réseau et le suivi nécessaires pour transformer un besoin en actions claires et coordonnées.</p><p data-reveal>Nous avançons avec une approche simple : comprendre l’objectif, mobiliser les bonnes personnes et maintenir une communication régulière pendant toute la collaboration.</p></div></div></section>
  <section className={styles.landmarks}><div className={styles.container}><h2 data-reveal>Ce qui structure notre travail.</h2><div className={styles.landmarkGrid}><article className={styles.experienceCard} data-reveal><RepereIcon type="experience"/><b>7</b><h3>Années d’expérience</h3><p>Une expérience construite au contact des réalités du terrain et des besoins des acteurs de la santé.</p></article><article className={styles.networkCard} data-reveal><RepereIcon type="network"/><h3>Réseau médical établi</h3><p>Une présence locale et un réseau mobilisable pour soutenir les missions confiées à Mahaty.</p></article><article className={styles.locationCard} data-reveal><RepereIcon type="location"/><h3>Présence à Bamako</h3><p>Des locaux, une équipe et une activité directement ancrés dans l’environnement malien.</p></article></div></div></section>
  <section className={styles.mission}><div className={styles.container}><span className={styles.eyebrow} data-reveal>Notre mission</span><h2 data-reveal>Faciliter la présence et l’organisation de nos partenaires au Mali.</h2><p className={styles.lead} data-reveal>Mahaty aide ses partenaires à disposer d’une équipe préparée, d’une représentation locale et d’un suivi administratif clair. L’objectif est de leur permettre de piloter leurs activités avec une meilleure visibilité sur les actions menées sur le terrain.</p><div className={styles.missionGrid}><Link data-reveal href="/services#formation"><span>01</span><h3>Former</h3><p>Préparer les délégués à présenter une offre avec clarté et professionnalisme.</p></Link><Link data-reveal href="/services#representation"><span>02</span><h3>Représenter</h3><p>Assurer une présence locale cohérente auprès des interlocuteurs concernés.</p></Link><Link data-reveal href="/services#gestion"><span>03</span><h3>Organiser</h3><p>Centraliser les informations, coordonner les actions et suivre leur avancement.</p></Link></div></div></section>
  <section className={styles.method} data-guide><div className={styles.container}><h2 data-reveal>Une collaboration simple, structurée et suivie.</h2><div className={styles.steps}>{[["01","Écouter","Nous clarifions votre objectif, votre offre et les résultats attendus."],["02","Organiser","Nous définissons les compétences, les actions et les outils de suivi nécessaires."],["03","Suivre","Nous coordonnons les actions et vous tenons informé de leur avancement."]].map(([n,t,p],i)=><article className={styles.guidedStep} key={n}><span>{n}</span><div><h3>— {t}</h3><p>{p}</p></div>{i<2&&<i>→</i>}</article>)}</div></div></section>
  <section className={styles.presence}><div className={styles.container}><h2 data-reveal>Une entreprise que vous pouvez voir et rencontrer.</h2><p data-reveal>Nos locaux, notre équipe et notre activité montrent la structure qui portera votre partenariat à Bamako.</p><div className={styles.gallery}><div className={styles.galleryLeft} data-reveal><Image src="/image/a-propos-presence-bureau.jpg" alt="Locaux de Mahaty Pharm à Bamako" fill sizes="(max-width:899px) 100vw, 380px"/></div><div data-reveal><Image src="/image/photo-equipe-a-propos.jpg" alt="Équipe de Mahaty Pharm" fill sizes="(max-width:899px) 100vw, 380px"/></div><div className={styles.galleryRight} data-reveal><Image src="/image/image-equipe-mahaty.jpg" alt="Activité de Mahaty Pharm" fill sizes="(max-width:899px) 100vw, 380px"/></div></div></div></section>
  <section className={styles.values}><div className={styles.container}><h2 data-reveal>Les principes que nous appliquons.</h2><div>{[["Clarté","Des objectifs définis, des actions compréhensibles et un suivi régulier."],["Proximité","Une équipe basée à Bamako et disponible pour comprendre les réalités locales."],["Sérieux","Une organisation professionnelle et une attention portée à chaque mission confiée."]].map(([t,p])=><article data-reveal key={t}><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
  <section className={styles.cta}><div data-reveal><h2>Construisons votre présence médicale au Mali.</h2><p>Vous recherchez un partenaire local pour former, représenter ou organiser votre activité ? Présentez-nous votre besoin.</p><div className={styles.actions}><Link className={`${styles.primary} ${styles.pulseButton}`} href="/contact">Présenter mon besoin</Link><a className={styles.secondary} href="https://wa.me/22377777777" target="_blank" rel="noopener noreferrer">WhatsApp : +223 77 77 77 77</a></div><a className={styles.email} href="mailto:Mahatycontact@gmail.com">Mahatycontact@gmail.com</a></div></section><Footer/><AboutMotionEffects/></main>}
